services:
  rabbitmq1:
    image: rabbitmq:management
    hostname: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitmq  # A shared secret for clustering
      - RABBITMQ_DEFAULT_USER=admin        # Set the default username
      - RABBITMQ_DEFAULT_PASS=password    # Set the default password
    ports:
      - "15671:15672"  # RabbitMQ management UI for node 1
      - "5671:5672"    # AMQP protocol
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - rabbitmq-net



  rabbitmq2:
    image: rabbitmq:management
    hostname: rabbitmq2
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitmq  # Same cookie for all nodes
      - RABBITMQ_DEFAULT_USER=admin        # Set the default username
      - RABBITMQ_DEFAULT_PASS=password    # Set the default password
    ports:
      - "15672:15672"  # RabbitMQ management UI for node 2
      - "5672:5672"    # AMQP protocol
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - rabbitmq-net
    depends_on:
      - rabbitmq1

  rabbitmq3:
    image: rabbitmq:management
    hostname: rabbitmq3
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitmq # Same cookie for all nodes
      - RABBITMQ_DEFAULT_USER=admin        # Set the default username
      - RABBITMQ_DEFAULT_PASS=password    # Set the default password
    ports:
      - "15673:15672"  # RabbitMQ management UI for node 3
      - "5673:5672"    # AMQP protocol
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - rabbitmq-net
    depends_on:
      - rabbitmq1

networks:
  rabbitmq-net:
    driver: bridge
