# MUST replace the 1.1.1.1 with the actual IP of upstream node
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq1
  namespace: rabbitmq-system
spec:
  replicas: 3
  # override:
  #   statefulSet:
  #     spec:
  #       podManagementPolicy: OrderedReady
  imagePullSecrets:
  - name: tanzu-rabbitmq-registry-creds
  rabbitmq:
    additionalPlugins:
      - rabbitmq_stream
      - rabbitmq_schema_definition_sync
      - rabbitmq_schema_definition_sync_prometheus
      - rabbitmq_standby_replication
    additionalConfig: |
      schema_definition_sync.operating_mode = upstream
      standby.replication.operating_mode = upstream
      # message stream retention limit (can either be size or time based), in this example, the size is 5G
      standby.replication.retention.size_limit.messages = 10000000
      # standby.replication.retention.time_limit.messages = 10m
      vm_memory_high_watermark.relative = 0.9
  resources:
    requests:
      cpu: 500m
      # cpu: 1
      memory: 2Gi
    limits:
      cpu: 500m
      # cpu: 1
      #memory: 500Mi
      memory: 2Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: upstream-secret
  namespace: rabbitmq-system
type: Opaque
stringData:
  username: test-user
  password: test-password

---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: rabbitmq-replicator
  namespace: rabbitmq-system
spec:
  rabbitmqClusterReference:
    name:  rabbitmq1 # the upstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.
  importCredentialsSecret:
    name: upstream-secret

---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-replicator.rabbitmq-schema-definition-sync.all
  namespace: rabbitmq-system
spec:
  vhost: "rabbitmq_schema_definition_sync" # name of a vhost
  userReference:
    name: rabbitmq-replicator
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq1  # the upstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.

---
apiVersion: rabbitmq.com/v1beta1
kind: SchemaReplication
metadata:
  name: rabbitmq1-schema
  namespace: rabbitmq-system  
spec:
  endpoints: "1.1.1.1:5672" # port 5672
  upstreamSecret:
    name: upstream-secret
  rabbitmqClusterReference:
    name: rabbitmq1  # the upstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.

---
apiVersion: rabbitmq.tanzu.vmware.com/v1beta1
kind: StandbyReplication
metadata:
  name: rabbitmq1-standby
  namespace: rabbitmq-system
spec:
  operatingMode: "upstream" # has to be "upstream" to configure an upstream RabbitMQ cluster; required value
  upstreamModeConfiguration: # list of policies that Operator will create
    replicationPolicies:
      - name: test-policy # policy name; required value
        pattern: "^.*" # any regex expression that will be used to match quorum queues name; required value
        vhost: "test" # vhost name; must be an existing vhost; required value
  rabbitmqClusterReference:
    name: rabbitmq1 # the upstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.

---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: default
  namespace: rabbitmq-system
spec:
  name: "test" # vhost name
  tags: ["standby_replication"]
  rabbitmqClusterReference:
    name: rabbitmq1 # the upstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.

---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-replicator.defaultvhost.all
  namespace: rabbitmq-system
spec:
  vhost: "test" # name of a vhost
  userReference:
    name: rabbitmq-replicator
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq1  # the upstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.

---
