---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: default
  namespace: rabbitmq-system
spec:
  name: "test" # vhost name
  tags: ["standby_replication"]
  rabbitmqClusterReference:
    name: xxxrabbitmq # the upstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.


---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-replicator.defaultvhost.all
  namespace: rabbitmq-system
spec:
  vhost: "test" # name of a vhost
  userReference:
    name: rabbitmq-replicator
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: xxxrabbitmq  # the upstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.

---
