apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tanzu-rabbitmq
spec:
  serviceAccountName: tanzu-rabbitmq
  packageRef:
    refName: rabbitmq.tanzu.vmware.com
    versionSelection:
      constraints: 3.13.3
