auth_backends.1 = rabbit_auth_backend_oauth2

management.oauth_enabled = true
management.oauth_client_id = O4hXbCJ73RSxyK88AKZ3aKFmACarVgGC(REPLACED)
management.oauth_scopes = 64fc0e0a129a0115ad0e1738(REPLACED)
management.oauth_provider_url = https://dev-akfzkkinmh0pq2b7.us.auth0.com(REPLACED)

auth_oauth2.resource_server_id = rabbitmq
auth_oauth2.preferred_username_claims.1 = user_name
auth_oauth2.additional_scopes_key = permissions
auth_oauth2.jwks_url = https://dev-akfzkkinmh0pq2b7.us.auth0.com/.well-known/jwks.json(REPLACED)
