services:
  node1:
    image: erlang
    container_name: node1
    command: erl -name node1@node1 -setcookie mycookie -setshortname true
    networks:
      - erlang-net
    tty: true
    stdin_open: true

  node2:
    image: erlang
    container_name: node2
    command: erl -name node2@node2 -setcookie mycookie -setshortname true
    networks:
      - erlang-net
    tty: true
    stdin_open: true

  node3:
    image: erlang
    container_name: node3
    command: erl -name node3@node3 -setcookie mycookie -setshortname true
    networks:
      - erlang-net
    tty: true
    stdin_open: true

networks:
  erlang-net:
    driver: bridge
