apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq1
  namespace: rabbitmq-system
spec:
  replicas: 1
  # imagePullSecrets:
  # - name: my-secret
  rabbitmq:
    additionalPlugins:
      - rabbitmq_auth_backend_ldap
    advancedConfig: |
      [
          {rabbit, [
              {auth_backends, [rabbit_auth_backend_ldap, rabbit_auth_backend_internal]}
              ]},

          {rabbitmq_auth_backend_ldap, [
              {servers, ["10.1.1.1"]},
              {port, 636},
              {use_ssl,     true},
              {ssl_options, [{cacertfile, "/etc/rabbitmq/certs/ca.crt"},
                      {certfile,   "/etc/rabbitmq/certs/client.crt"},
                      {keyfile,    "/etc/rabbitmq/certs/client.key"},
                      %% Disables peer certificate chain verification.
                      %%
                      %% Doing so loses one of the key benefits of TLS and make the setup less secure
                      %% but also significantly simplifies node configuration.
                      {verify, verify_none}
                      %%{server_name_indication, "ldap.identity.eng.megacorp.local"},
                      %%{ssl_hostname_verification, wildcard}
              ]},
              {user_dn_pattern, "uid=${username},ou=People,dc=example,dc=com"},
              {tag_queries, [
                  {administrator, {constant, true}},
                  {management, {constant, true}}
              ]},
              {log, network}
          ]}

      ].
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: rabbitmq
                volumeMounts:
                  - name: ldap-certs
                    mountPath: /etc/rabbitmq/certs
                    readOnly: true
            volumes:
              - name: ldap-certs
                secret:
                  secretName: rabbitmq-ldap-tls
                  defaultMode: 420
  resources:
    limits:
      cpu: 100m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 1Gi
