---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq1
  namespace: rabbitmq-system
spec:
  replicas: 1
  imagePullSecrets:
  - name: tanzu-rabbitmq-registry-creds
  rabbitmq:
    additionalPlugins:
      - rabbitmq_stream
      - rabbitmq_schema_definition_sync
      - rabbitmq_schema_definition_sync_prometheus
      - rabbitmq_standby_replication
      - rabbitmq_warm_standby
    additionalConfig: |
      #log.console.level = debug
      schema_definition_sync.operating_mode = upstream
      schema_definition_sync.connection.endpoints.one = localhost:5672
      schema_definition_sync.connection.username = test-user
      schema_definition_sync.connection.password = test-password
      standby.replication.operating_mode = upstream
      standby.replication.connection.endpoints.one = localhost:5552
      standby.replication.connection.username = test-user
      standby.replication.connection.password = test-password
      # message stream retention limit (can either be size or time based)
      standby.replication.retention.size_limit.messages = 5000000000
      # standby.replication.retention.time_limit.messages = 12h
  resources:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      cpu: 100m
      memory: 500Mi




# This user is used from the downstream (standby) cluster to establish a connection and manage the replication
---
apiVersion: v1
kind: Secret
metadata:
  name: upstream-secret
type: Opaque
stringData:
  username: test-user
  password: test-password

---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: rabbitmq-replicator
spec:
  rabbitmqClusterReference:
    name:  rabbitmq1 # the upstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.
  importCredentialsSecret:
    name: upstream-secret




# The rabbitmq_schema_definition_sync virtual host is created when the cluster is created.
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-replicator.rabbitmq-schema-definition-sync.all
  namespace: rabbitmq-system
spec:
  vhost: "rabbitmq_schema_definition_sync" # name of a vhost
  userReference:
    name: rabbitmq-replicator
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq1  # the upstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.


# add another vhost
---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: default
  namespace: rabbitmq-system
spec:
  name: "test" # vhost name
  tags: ["standby_replication"]
  rabbitmqClusterReference:
    name: rabbitmq1 # the upstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.


---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-replicator.rabbitmq-schema-definition-sync.test
  namespace: rabbitmq-system
spec:
  vhost: "test" # name of a vhost
  userReference:
    name: rabbitmq-replicator
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq1  # the upstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.
