---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq1
  namespace: rabbitmq-system
spec:
  replicas: 1
  imagePullSecrets:
  - name: tanzu-rabbitmq-registry-creds
  rabbitmq:
    additionalPlugins:
      - rabbitmq_stream
      - rabbitmq_schema_definition_sync
      - rabbitmq_schema_definition_sync_prometheus
      - rabbitmq_standby_replication
      - rabbitmq_warm_standby
    additionalConfig: |
      #log.console.level = debug
      schema_definition_sync.operating_mode = upstream
      schema_definition_sync.connection.endpoints.one = localhost:5672
      schema_definition_sync.connection.username = test-user
      schema_definition_sync.connection.password = test-password
      standby.replication.operating_mode = upstream
      standby.replication.connection.endpoints.one = localhost:5552
      standby.replication.connection.username = test-user
      standby.replication.connection.password = test-password
      # message stream retention limit (can either be size or time based)
      standby.replication.retention.size_limit.messages = 5000000000
      # standby.replication.retention.time_limit.messages = 12h
  resources:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      cpu: 100m
      memory: 500Mi
