auth_backends.1 = rabbit_auth_backend_oauth2
auth_backends.2 = internal

auth_oauth2.resource_server_id = rabbitmq
auth_oauth2.verify_aud = false
auth_oauth2.https.peer_verification = verify_none

auth_oauth2.preferred_username_claims.1 = preferred_username
auth_oauth2.preferred_username_claims.2 = client_id


auth_oauth2.additional_scopes_key = extra_scopes


management.oauth_enabled = true
management.oauth_client_id = rabbitmq-client
# management.oauth_client_secret = your-client-secret-here
management.oauth_client_secret = VHdTDh7ZugTk98fC2vVbKvjTzfrpJjJW

# The BACKEND uses Caddy to validate tokens securely
auth_oauth2.issuer = https://caddy:8443/realms/rabbitmq
auth_oauth2.jwks_url = https://caddy:8443/realms/rabbitmq/protocol/openid-connect/certs

# The FRONTEND (browser) uses this to find Keycloak
management.oauth_provider_url = http://localhost:8080/realms/rabbitmq
