spring.application.name=myproject


spring.rabbitmq.host=localhost
spring.rabbitmq.username=admin
spring.rabbitmq.password=password

# This tells Spring Boot to activate publisher confirms on the underlying channels
spring.rabbitmq.publisher-confirm-type=correlated
