services:
  shanghai:
    image: rabbitmq:management
    hostname: shanghai
    container_name: shanghai
    environment:
      - RABBITMQ_DEFAULT_USER=admin        # Set the default username
      - RABBITMQ_DEFAULT_PASS=password    # Set the default password
    ports:
      - "15672:15672"  # RabbitMQ management
      - "5672:5672"    # AMQP protocol
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - rabbitmq-net

  beijing:
    image: rabbitmq:management
    hostname: beijing
    container_name: beijing
    environment:
      - RABBITMQ_DEFAULT_USER=admin        # Set the default username
      - RABBITMQ_DEFAULT_PASS=password    # Set the default password
    ports:
      - "15772:15672"  # RabbitMQ management
      - "5772:5672"    # AMQP protocol
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - rabbitmq-net

  perf-test:
    image: pivotalrabbitmq/perf-test:latest
    hostname: perf-test
    container_name: perf-test
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      - rabbitmq-net

networks:
  rabbitmq-net:
    driver: bridge
