web_mqtt.ssl.port       = 15676
web_mqtt.ssl.backlog    = 1024
web_mqtt.ssl.cacertfile = /etc/rabbitmq/certs/myca.crt
web_mqtt.ssl.certfile   = /etc/rabbitmq/certs/myserver.crt
web_mqtt.ssl.keyfile    = /etc/rabbitmq/certs/myserver.key


web_stomp.ssl.port       = 15673
web_stomp.ssl.backlog    = 1024
web_stomp.ssl.cacertfile = /etc/rabbitmq/certs/myca.crt
web_stomp.ssl.certfile   = /etc/rabbitmq/certs/myserver.crt
web_stomp.ssl.keyfile    = /etc/rabbitmq/certs/myserver.key

