services:
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin        # Set the default username
      - RABBITMQ_DEFAULT_PASS=password    # Set the default password
    ports:
      - "15672:15672"  # RabbitMQ management
      - "5672:5672"    # AMQP protocol
      - "15692:15692"  # prometheus
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - rabbitmq-net

  prometheus:
    image: prom/prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    networks:
      - rabbitmq-net

  grafana:
    image: grafana/grafana-enterprise
    hostname: grafana
    ports:
      - "3000:3000"
    networks:
      - rabbitmq-net

networks:
  rabbitmq-net:
    driver: bridge


