global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      #- targets: ['rabbitmq:15692']
      - targets:
          - 'rabbitmq:15692'


  - job_name: gemfire-management-console
    scrape_interval: 2s
    scrape_timeout: 2s
    http_sd_configs:
      # URL must contain the location from which the targets are fetched.
      - url: "http://localhost:8080/v1/prometheus-targets"
        refresh_interval: 5s
