services:
  node1:
    image: rabbitmq:4.1.0-management
    hostname: node1
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitmq  # A shared secret for clustering
      - RABBITMQ_DEFAULT_USER=admin        # Set the default username
      - RABBITMQ_DEFAULT_PASS=password    # Set the default password
    volumes:
      - ./node1:/var/lib/rabbitmq/mnesia/rabbit@node1
    ports:
      - "15672:15672"  # RabbitMQ management UI for node 1
      - "5672:5672"    # AMQP protocol
    networks:
      - rabbitmq-net


networks:
  rabbitmq-net:
    driver: bridge
