spring.application.name=myproject


spring.rabbitmq.host=localhost
spring.rabbitmq.username=admin
spring.rabbitmq.password=password
# By default, publisher confirms are disabled in Spring Boot. 
# We explicitly set it to 'none' here to strictly match your intent.
spring.rabbitmq.publisher-confirm-type=none
