https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit/docs/rabbitmq.conf.example








# management ssl

management.ssl.port       = 15671
management.ssl.cacertfile = /tmp/ca.crt
management.ssl.certfile   = /tmp/server.crt
management.ssl.keyfile    = /tmp/server.key
## This key must only be used if private key is password protected
# management.ssl.password   = bunnies






# internal node communication
listeners.tcp = none
listeners.ssl.default = 5671
ssl_options.cacertfile = /tmp/ca.crt
ssl_options.certfile = /tmp/tls.crt
ssl_options.keyfile = /tmp/tls.key
ssl_options.verify = verify_peer
ssl_options.fail_if_no_peer_cert = true



# rabbitmq cluster formation
cluster_formation.peer_discovery_backend = rabbit_peer_discovery_classic_config
cluster_formation.classic_config.nodes.1 = rabbit@rabbitmq1
cluster_formation.classic_config.nodes.2 = rabbit@rabbitmq2
cluster_formation.classic_config.nodes.3 = rabbit@rabbitmq3



cluster_partition_handling = pause_minority



# log rotation
log.file.rotation.date = $D11




# stream ssl
ssl_options.cacertfile = /path/to/tls/ca_certificate.pem
ssl_options.certfile   = /path/to/tls/server_certificate.pem
ssl_options.keyfile    = /path/to/tls/server_key.pem
ssl_options.verify     =  verify_peer
ssl_options.fail_if_no_peer_cert = true

stream.listeners.tcp.1 = 5552
# default TLS-enabled port for stream connections
stream.listeners.ssl.1 = 5551















/etc/rabbitmq/rabbitmq.conf


max_message_size = 10000000



# enable mgmt https

management.ssl.port       = 15671
management.ssl.cacertfile = /tmp/ca.crt
management.ssl.certfile   = /tmp/tls.crt
management.ssl.keyfile    = /tmp/tls.key





# enable amqp/ssl

listeners.ssl.default = 5671

ssl_options.cacertfile = /tmp/ca.crt
ssl_options.certfile   = /tmp/tls.crt
ssl_options.keyfile    = /tmp/tls.key
ssl_options.verify     = verify_peer
ssl_options.fail_if_no_peer_cert = true













default_user = xxx
default_pass = xxx
default_user_tags.administrator = true






systemctl restart rabbitmq-server.service

journalctl -xeu rabbitmq-server.service





openssl s_client -connect localhost:15671


