https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit/docs/rabbitmq.conf.example









max_message_size = 10000000



# enable the mgmt https

management.ssl.port       = 15671
management.ssl.cacertfile = /tmp/domain.crt
management.ssl.certfile   = /tmp/domain.crt
management.ssl.keyfile    = /tmp/domain.key





default_user = xxx
default_pass = xxx
default_user_tags.administrator = true
