apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: rabbitmq
  ports:
  - name: locator
    protocol: TCP
    port: 5672       # external port
    targetPort: 5672  # container port
