services:
  node1:
    image: erlang
    container_name: node1
    hostname: node1
    networks:
      erlang-net:
        aliases: [node1]
    tty: true

  node2:
    image: erlang
    container_name: node2
    hostname: node2
    networks:
      erlang-net:
        aliases: [node2]
    tty: true

  node3:
    image: erlang
    container_name: node3
    hostname: node3
    networks:
      erlang-net:
        aliases: [node3]
    tty: true

networks:
  erlang-net:
    driver: bridge
