apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq1
  # namespace: rabbitmq-system
spec:
  replicas: 1
  # imagePullSecrets:
  # - name: tanzu-rabbitmq-registry-creds
  resources:
    limits:
      cpu: 100m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 1Gi
  override:
    statefulSet:
      spec:
        template:
          spec:
            securityContext:
              runAsNonRoot: true
            initContainers:
            - name: setup-container
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
                seccompProfile:
                  type: RuntimeDefault
            containers:
              - name: rabbitmq
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  seccompProfile:
                    type: RuntimeDefault
