services:

  node2:
    # image: rabbitmq:management
    image: rabbitmq:3.13.7-management
    hostname: node2
    container_name: node2
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitmq  # Same cookie for all nodes
      - RABBITMQ_DEFAULT_USER=admin        # Set the default username
      - RABBITMQ_DEFAULT_PASS=password    # Set the default password
    ports:
      - "15672:15672"  # RabbitMQ management UI for node 2
      - "5672:5672"    # AMQP protocol
      - 5552:5552
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
  # Mounts the local ./data folder to the container's RabbitMQ data path
      - ./node2:/var/lib/rabbitmq
    networks:
      - rabbitmq-net



  perf-test:
      image: pivotalrabbitmq/perf-test:latest
      container_name: rabbit-perf-test
      entrypoint: ["sh", "-c", "sleep infinity"]
      networks:
        - rabbitmq-net
      depends_on:
        - node2


networks:
  rabbitmq-net:
    driver: bridge
