services:
  rabbitmq-up:
    image: rabbitmq:management
    hostname: rabbitmq-up
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitmq  # A shared secret for clustering
      - RABBITMQ_DEFAULT_USER=admin        # Set the default username
      - RABBITMQ_DEFAULT_PASS=password    # Set the default password
    ports:
      - "15671:15672"  # RabbitMQ management UI
      - "5671:5672"    # AMQP protocol
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - rabbitmq-net

  rabbitmq-down:
    image: rabbitmq:management
    hostname: rabbitmq-down
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitmq  # A shared secret for clustering
      - RABBITMQ_DEFAULT_USER=admin        # Set the default username
      - RABBITMQ_DEFAULT_PASS=password    # Set the default password
    ports:
      - "15672:15672"  # RabbitMQ management UI
      - "5672:5672"    # AMQP protocol
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - rabbitmq-net



networks:
  rabbitmq-net:
    driver: bridge
