# 1. Define the authentication chain
auth_backends.1 = ldap
auth_backends.2 = internal

# 2. LDAP Server Connection Settings
auth_ldap.servers.1 = openldap
auth_ldap.port      = 389

# 3. LDAP User Structure
# auth_ldap.user_dn_pattern = cn=${username},ou=users,dc=example,dc=com
auth_ldap.user_dn_pattern = uid=${username},ou=users,dc=example,dc=com
