services: Docker Desktop   o View Config   w Enable Watch
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitmq  # A shared secret for clustering
      - RABBITMQ_DEFAULT_USER=admin        # Set the default username
      - RABBITMQ_DEFAULT_PASS=password    # Set the default password
    ports:
      - "15672:15672"  # RabbitMQ management
      - "5672:5672"    # AMQP protocol
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - rabbitmq-net



  openldap:
    image: bitnami/openldap:latest
    hostname: openldap
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=password
      - LDAP_ENABLE_TLS=yes
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password,password
      - LDAP_ROOT=dc=example,dc=com
      - LDAP_ADMIN_DN=cn=admin,dc=example,dc=com
      - LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/ldap.crt
      - LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/ldap.key
      - LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/ca.crt
    volumes:
      - ./ldap.crt:/opt/bitnami/openldap/certs/ldap.crt
      - ./ldap.key:/opt/bitnami/openldap/certs/ldap.key
      - ./ca.crt:/opt/bitnami/openldap/certs/ca.crt
    ports:
      - "1389:1389"
      - "1636:1636"
    networks:
      - rabbitmq-net
    depends_on:
      - rabbitmq

networks:
  rabbitmq-net:
    driver: bridge
