services:
  rabbitmq1:
    image: rabbitmq.packages.broadcom.com/vmware-tanzu-rabbitmq:4.0.7
    hostname: rabbitmq1
    environment:
      - RABBITMQ_DEFAULT_USER=admin        # Set the default username
      - RABBITMQ_DEFAULT_PASS=password    # Set the default password
    ports:
      - "15671:15672"  # RabbitMQ management UI for node 1
      - "5671:5672"    # AMQP protocol
      - "5551:5552"    
    networks:
      - rabbitmq-net



  rabbitmq2:
    image: rabbitmq.packages.broadcom.com/vmware-tanzu-rabbitmq:4.0.7
    hostname: rabbitmq2
    environment:
      - RABBITMQ_DEFAULT_USER=admin        # Set the default username
      - RABBITMQ_DEFAULT_PASS=password    # Set the default password
    ports:
      - "15672:15672"  # RabbitMQ management UI for node 2
      - "5672:5672"    # AMQP protocol
      - "5552:5552"    # AMQP protocol
    networks:
      - rabbitmq-net
    depends_on:
      - rabbitmq1


networks:
  rabbitmq-net:
    driver: bridge
