apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: my-tanzu-rabbit
  namespace: rabbitmq-system
spec:
  replicas: 1
  tls:
    secretName: tls-secret
  imagePullSecrets:
  - name: tanzu-rabbitmq-registry-creds
  resources:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      cpu: 100m
      #cpu: 1
      #memory: 500Mi
      memory: 2Gi
