apiVersion: v1
kind: Secret
metadata:
  name: upstream-secret
  namespace: rabbitmq-system
type: Opaque
stringData:
  username: test-user
  password: test-password
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: rabbitmq-replicator
  namespace: rabbitmq-system
spec:
  rabbitmqClusterReference:
    name:  upstream-rabbit # the upstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.
  importCredentialsSecret:
    name: upstream-secret
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-replicator.rabbitmq-schema-definition-sync.all
  namespace: rabbitmq-system
spec:
  vhost: "rabbitmq_schema_definition_sync" # name of a vhost
  userReference:
    name: rabbitmq-replicator
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: upstream-rabbit  # the upstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.
---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: default
  namespace: rabbitmq-system
spec:
  name: "test" # vhost name
  tags: ["standby_replication"]
  rabbitmqClusterReference:
    name: upstream-rabbit
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-replicator.rabbitmq-schema-definition-sync.test
  namespace: rabbitmq-system
spec:
  vhost: "test" # name of the vhost
  userReference:
    name: rabbitmq-replicator
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: upstream-rabbit  # the upstream RabbitMQ cluster name. It must be in the same namespace and it is a mandatory value.
---
apiVersion: rabbitmq.com/v1beta1
kind: Policy
metadata:
  name: upstream-policy
  namespace: rabbitmq-system
spec:
  name: osr # name of the policy
  vhost: "test" # default to '/' if not provided
  pattern: "^.*" # regex used to match queues and exchanges
  applyTo: "queues" # set to 'queues', 'exchanges', or 'all'
  definition: # policy definition
    remote-dc-replicate: true
  rabbitmqClusterReference:
    name: upstream-rabbit # rabbitmqCluster must exist in the same namespace as this resource
